# Generated by Django 3.2.4 on 2021-07-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20210727_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
