# Generated by Django 3.2.4 on 2021-07-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='main_photo',
            field=models.ImageField(upload_to='media/Properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/Properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/Properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/Properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/Properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='media/Properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='media/Properties/'),
        ),
    ]
