# Generated by Django 3.2.4 on 2021-07-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_rename_main_photo_property_mainphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='MainPhoto',
            field=models.ImageField(height_field='1280', upload_to='Properties/', width_field='1920'),
        ),
    ]
