# Generated by Django 3.2.4 on 2021-08-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20210730_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_status',
            field=models.CharField(choices=[('FS', 'For Sale'), ('FR', 'For Rent'), ('SO', 'Sold Out')], max_length=2, verbose_name='Property status'),
        ),
    ]
