# Generated by Django 3.2.4 on 2021-10-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_property_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(verbose_name='Bedrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='garage',
            field=models.PositiveIntegerField(default=0, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sqft',
            field=models.PositiveIntegerField(verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
