# Generated by Django 3.2.4 on 2021-11-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20211017_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Nor', 'Normal'), ('Exc', 'Exclusive')], default='Nor', max_length=3),
        ),
    ]
